<?php
class stopwordV2{
    // List of common English stopwords stored as keys for fast lookup
    // List gathered from NLTK stopwords library
    public $stopwords = [
        'a' => true,
        'about' => true,
        'above' => true,
        'after' => true,
        'again' => true,
        'against' => true,
        'ain' => true,
        'all' => true,
        'am' => true,
        'an' => true,
        'and' => true,
        'any' => true,
        'are' => true,
        'aren' => true,
        'aren\'t' => true,
        'as' => true,
        'at' => true,
        'be' => true,
        'because' => true,
        'been' => true,
        'before' => true,
        'being' => true,
        'below' => true,
        'between' => true,
        'both' => true,
        'but' => true,
        'by' => true,
        'can' => true,
        'couldn' => true,
        'couldn\'t' => true,
        'd' => true,
        'did' => true,
        'didn' => true,
        'didn\'t' => true,
        'do' => true,
        'does' => true,
        'doesn' => true,
        'doesn\'t' => true,
        'doing' => true,
        'don' => true,
        'don\'t' => true,
        'down' => true,
        'during' => true,
        'each' => true,
        'few' => true,
        'for' => true,
        'from' => true,
        'further' => true,
        'had' => true,
        'hadn' => true,
        'hadn\'t' => true,
        'has' => true,
        'hasn' => true,
        'hasn\'t' => true,
        'have' => true,
        'haven' => true,
        'haven\'t' => true,
        'having' => true,
        'he' => true,
        'he\'d' => true,
        'he\'ll' => true,
        'her' => true,
        'here' => true,
        'hers' => true,
        'herself' => true,
        'he\'s' => true,
        'him' => true,
        'himself' => true,
        'his' => true,
        'how' => true,
        'i' => true,
        'i\'d' => true,
        'if' => true,
        'i\'ll' => true,
        'i\'m' => true,
        'in' => true,
        'into' => true,
        'is' => true,
        'isn' => true,
        'isn\'t' => true,
        'it' => true,
        'it\'d' => true,
        'it\'ll' => true,
        'it\'s' => true,
        'its' => true,
        'itself' => true,
        'i\'ve' => true,
        'just' => true,
        'll' => true,
        'm' => true,
        'ma' => true,
        'me' => true,
        'mightn' => true,
        'mightn\'t' => true,
        'more' => true,
        'most' => true,
        'mustn' => true,
        'mustn\'t' => true,
        'my' => true,
        'myself' => true,
        'needn' => true,
        'needn\'t' => true,
        'no' => true,
        'nor' => true,
        'not' => true,
        'now' => true,
        'o' => true,
        'of' => true,
        'off' => true,
        'on' => true,
        'once' => true,
        'only' => true,
        'or' => true,
        'other' => true,
        'our' => true,
        'ours' => true,
        'ourselves' => true,
        'out' => true,
        'over' => true,
        'own' => true,
        're' => true,
        's' => true,
        'same' => true,
        'shan' => true,
        'shan\'t' => true,
        'she' => true,
        'she\'d' => true,
        'she\'ll' => true,
        'she\'s' => true,
        'should' => true,
        'shouldn' => true,
        'shouldn\'t' => true,
        'should\'ve' => true,
        'so' => true,
        'some' => true,
        'such' => true,
        't' => true,
        'than' => true,
        'that' => true,
        'that\'ll' => true,
        'the' => true,
        'their' => true,
        'theirs' => true,
        'them' => true,
        'themselves' => true,
        'then' => true,
        'there' => true,
        'these' => true,
        'they' => true,
        'they\'d' => true,
        'they\'ll' => true,
        'they\'re' => true,
        'they\'ve' => true,
        'this' => true,
        'those' => true,
        'through' => true,
        'to' => true,
        'too' => true,
        'under' => true,
        'until' => true,
        'up' => true,
        've' => true,
        'very' => true,
        'was' => true,
        'wasn' => true,
        'wasn\'t' => true,
        'we' => true,
        'we\'d' => true,
        'we\'ll' => true,
        'we\'re' => true,
        'were' => true,
        'weren' => true,
        'weren\'t' => true,
        'we\'ve' => true,
        'what' => true,
        'when' => true,
        'where' => true,
        'which' => true,
        'while' => true,
        'who' => true,
        'whom' => true,
        'why' => true,
        'will' => true,
        'with' => true,
        'won' => true,
        'won\'t' => true,
        'wouldn' => true,
        'wouldn\'t' => true,
        'y' => true,
        'you' => true,
        'you\'d' => true,
        'you\'ll' => true,
        'your' => true,
        'you\'re' => true,
        'yours' => true,
        'yourself' => true,
        'yourselves' => true,
        'you\'ve' => true
    ];
    //Array to hold the filtered words after stopwords removal
    public $filteredArr = [];

    // Constructor accepts an array of words to filter
    public function __construct($strArr) {
        // Loop through each word in input array
        foreach($strArr as $word) {
            // Check if the word is NOT a stopword
            if (!isset($this->stopwords[$word])) {
                // If not a stopword, add it to filteredArr
                $this->filteredArr[] = $word;
            }
        }
    }

    // Getter method to return the filtered words
    public function getStopwordsV2() {
        return $this->filteredArr;
    }
}
?>