-- ============================
-- FAQUiaChatbot SEEDER
-- ============================

USE FAQUiaChatbot;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE questionLog;
TRUNCATE TABLE questions;
TRUNCATE TABLE category;
TRUNCATE TABLE keyWords;
TRUNCATE TABLE chatUser;


-- 2) keyWords
INSERT INTO keyWords (keyword) VALUES
('map'),
('information'),
('direction'),
('campus'),
('building'),
('room'),
('navigation'),
('path'),
('road'),
('location'),
('exam'),
('date'),
('schedule'),
('studentweb'),
('study'),
('test'),
('submission'),
('deadline'),
('semester'),
('assessment'),
('activity'),
('sport'),
('culture'),
('association'),
('event'),
('student'),
('social'),
('course'),
('workshop'),
('meeting'),
('address'),
('Kristiansand'),
('Grimstad'),
('university'),
('uia'),
('parking'),
('space'),
('car'),
('staff'),
('area'),
('find'),
('spot'),
('park'),
('register'),
('sign'),
('table'),
('timetable'),
('overview'),
('submit'),
('assignment'),
('deliverable'),
('deliver'),
('send'),
('bug'),
('software'),
('problem'),
('pc'),
('issue'),
('technical'),
('help'),
('it'),
('support'),
('login'),
('grade'),
('result'),
('final'),
('time'),
('book'),
('available'),
('reserve'),
('capacity'),
('near'),
('coffe'),
('food'),
('cafe'),
('close'),
('place'),
('bite'),
('join'),
('club'),
('group'),
('membership'),
('organization'),
('navigate'),
('route'),
('where'),
('mazemap'),
('search'),
('offer'),
('contact'),
('email'),
('phone'),
('reach'),
('professor'),
('teacher'),
('start'),
('begin'),
('year'),
('calendar'),
('health'),
('medical'),
('advice'),
('exchange'),
('abroad'),
('program'),
('international'),
('uplaod'),
('process'),
('instruction'),
('card'),
('id'),
('get'),
('accsess'),
('report'),
('error');


-- 3) categories
INSERT INTO category (categoryDescription) VALUES
('Study Administration'),
('IT and Technical Support'),
('Exams and Assessment'),
('Campus and Student Life'),
('International and Exchange'),
('Health and Counseling');


-- 4) 30 questions with lemma keywords
INSERT INTO questions (questionDescription, questionAnswer, keyword1, keyword2, keyword3, keyword4, keyword5, keyword6, keyword7, keyword8, keyword9, keyword10, category)
VALUES
('How do I find my way?', 'Use the map on UiA website or ask at the information desk.', 1, 41, 3, 4, 5, 6, 7, 8, 9, 10, 1),
('When are the exams?', 'Exam dates are on Studentweb and in your study plan.', 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 3),
('What activity is available?', 'UiA offers many activities: sport, culture, student association, and social events.', 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 4),
('Where is UiA located?', 'Main campus in Kristiansand, campus in Grimstad.', 31, 32, 33, 34, 35, 4, 1, 10, NULL, NULL, 4),
('Is there parking?', 'Parking spaces available for staff and student; see parking map.', 38, 39, 40, 4, 26, 41, 8, 36, 42, 43, 4),
('How can I register for a course?', 'Course registration is done via Studentweb.', 14, 28, 15, 26, 13, 44, 45, NULL, NULL, NULL, 1),
('Where can I find the schedule?', 'The semester schedule is on Studentweb and course page.', 12, 19, 14, 13, 28, 47, 48, NULL, NULL, NULL, 1),
('How do I submit an assignment?', 'Submit your test or assignment through Studentweb.', 16, 49, 18, 14, 15, 50, 51, 52, 53, NULL, 1),
('Who can help with IT problem?', 'IT and technical support can assist.', 54, 55, 56, 57, 58, 59, 60, 61, 62, NULL, 2),
('How do I access Studentweb?', 'Login to Studentweb with your student account.', 14, 26, 15, 63, 64, 65, NULL, NULL, NULL, NULL, 2),
('When is the next exam?', 'Check the exam date in Studentweb.', 11, 12, 14, 15, 66, 18, 67, NULL, NULL, NULL, 3),
('How many room are available?', 'Rooms can be booked through campus portal.', 6, 5, 4, 68, 69, 70, 71, NULL, NULL, NULL, 4),
('Where is the nearest cafe?', 'Campus area has cafe near the building.', 75, 73, 40, 72, 78, 74, 4, 76, 77, NULL, 4),
('How do I join student association?', 'Sign up via the student union.', 26, 24, 25, 79, 80, 44, 81, 80, 82, 83, 4),
('How to find direction to building?', 'Use navigation tools or campus map.', 3, 5, 1, 84, 85, 1, 86, 87, NULL, NULL, 4),
('How do I find campus address?', 'Address available on UiA website.', 31, 32, 30, 1, 88, NULL, NULL, NULL, NULL, NULL, 4),
('Where is parking area?', 'Parking area for staff and student is marked.', 38, 40, 39, 4, 43, 40, 37, 10, NULL, NULL, 4),
('Which sport are offered?', 'Sport activities listed on campus portal.', 22, 89, 4, 79, 69, NULL, NULL, NULL, NULL, NULL, 4),
('How to participate in event?', 'Sign up for student event.', 25, 26, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4),
('What culture activity is there?', 'Culture and social activities available.', 23, 26, 27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4),
('How do I contact staff?', 'Staff can be contacted via email or office.', 90, 39, 91, 92, 93, 62, 94, 95, 60, 2, 4),
('Where is my room?', 'Check room number in Studentweb.', 6, 10, 41, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4),
('How to get directions to campus?', 'Follow path or road; use campus map.', 3, 8, 9, 4, 1, NULL, NULL, NULL, NULL, NULL, 4),
('When is the semester start?', 'Semester start date available on Studentweb.', 96, 12, 97, 13, 19, 98, 99, NULL, NULL, NULL, 1),
('How do I check deadline?', 'Submission deadline available in course page.', 18, 17, 19, 28, NULL, NULL, NULL, NULL, NULL, NULL, 1),
('What workshop is available?', 'Workshop registration is open via Studentweb.', 29, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4),
('How to schedule meeting?', 'Meeting can be scheduled via Studentweb or email.', 30, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
('Who can I ask about health?', 'Health and counseling services are available.', 2, 100, 60, 62, 101, 102, 90, NULL, NULL, NULL, 6),
('How do I find exam location?', 'Check exam room and building via Studentweb.', 11, 6, 5, 41, 6, 77, NULL, NULL, NULL, NULL, 3),
('Can I get international exchange info?', 'Exchange info available via International office.', 103, 104, 103, 105, 2, 106, NULL, NULL, NULL, NULL, 5),
('How to access parking map?', 'Parking map available on UiA website.', 1, 38, 39, 43, NULL, NULL, NULL, NULL, NULL, NULL, 4),
('What is the submission process?', 'Submission process described in course page.', 49, 52, 107, 108, 50, 18, 109, NULL, NULL, NULL, 1),
('How can I get student card?', 'Student card issued at information desk.', 110, 111, 112, 113, 26, NULL, NULL, NULL, NULL, NULL, 4),
('How do I report issue?', 'Report problem to IT support.', 114, 58, 56, 60, 115, 54, 90, NULL, NULL, NULL, 2),
('how do i contact staff?', 'staff can be contacted via email or office.', 90, 39, 91, 92, 93, 62, 94, NULL, NULL, NULL, NULL);
SET FOREIGN_KEY_CHECKS = 1;